-- HealthCoach AI — Initial Schema
-- Run this in your Supabase SQL editor or via Supabase CLI

-- 1. Profiles table (extends Supabase Auth)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  full_name text,
  birth_date date,
  sex text check (sex in ('male', 'female')),
  current_weight decimal,
  height decimal,
  activity_level text check (activity_level in ('sedentary', 'moderate', 'active')),
  tdee integer,
  target_calories integer,
  target_water_ml integer default 2500
);

-- 2. Food logs
create table if not exists public.food_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  food_name text not null,
  meal_type text check (meal_type in ('breakfast', 'lunch', 'dinner', 'snack')),
  calories integer not null,
  protein decimal,
  carbs decimal,
  fat decimal
);

-- 3. Water logs
create table if not exists public.water_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  date date default current_date not null,
  amount_ml integer not null
);

-- 4. Weight history
create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  date date default current_date not null,
  weight decimal not null,
  unique(user_id, date)
);

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.food_logs enable row level security;
alter table public.water_logs enable row level security;
alter table public.weight_logs enable row level security;

-- Profiles policies
create policy "Users can view own profile"
  on public.profiles for select using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

-- Food logs policies
create policy "Users can view own food logs"
  on public.food_logs for select using (auth.uid() = user_id);

create policy "Users can insert own food logs"
  on public.food_logs for insert with check (auth.uid() = user_id);

create policy "Users can delete own food logs"
  on public.food_logs for delete using (auth.uid() = user_id);

-- Water logs policies
create policy "Users can view own water logs"
  on public.water_logs for select using (auth.uid() = user_id);

create policy "Users can insert own water logs"
  on public.water_logs for insert with check (auth.uid() = user_id);

-- Weight logs policies
create policy "Users can view own weight logs"
  on public.weight_logs for select using (auth.uid() = user_id);

create policy "Users can insert own weight logs"
  on public.weight_logs for insert with check (auth.uid() = user_id);

create policy "Users can update own weight logs"
  on public.weight_logs for update using (auth.uid() = user_id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Indexes for performance
create index if not exists food_logs_user_created_idx on public.food_logs(user_id, created_at);
create index if not exists water_logs_user_date_idx on public.water_logs(user_id, date);
create index if not exists weight_logs_user_date_idx on public.weight_logs(user_id, date);
