-- HealthCoach AI — Neon PostgreSQL schema
-- Run this in your Neon SQL editor

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  birth_date DATE,
  sex TEXT CHECK (sex IN ('male', 'female')),
  height_cm NUMERIC(5,1),
  current_weight NUMERIC(5,2),
  activity_level TEXT CHECK (activity_level IN ('sedentary', 'light', 'moderate', 'active', 'very_active')),
  tdee INTEGER,
  target_calories INTEGER,
  target_protein_g NUMERIC(5,1),
  target_carbs_g NUMERIC(5,1),
  target_fat_g NUMERIC(5,1),
  target_water_ml INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS food_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  food_name TEXT NOT NULL,
  meal_type TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')),
  calories INTEGER NOT NULL CHECK (calories >= -5000 AND calories <= 5000),
  protein NUMERIC(6,2) CHECK (protein >= 0),
  carbs NUMERIC(6,2) CHECK (carbs >= 0),
  fat NUMERIC(6,2) CHECK (fat >= 0),
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS water_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount_ml INTEGER NOT NULL CHECK (amount_ml > 0 AND amount_ml <= 2000),
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS weight_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  weight_kg NUMERIC(5,2) NOT NULL CHECK (weight_kg > 0 AND weight_kg < 500),
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, log_date)
);

CREATE INDEX IF NOT EXISTS idx_food_logs_user_date ON food_logs(user_id, log_date);
CREATE INDEX IF NOT EXISTS idx_water_logs_user_date ON water_logs(user_id, log_date);
CREATE INDEX IF NOT EXISTS idx_weight_logs_user_date ON weight_logs(user_id, log_date);

-- PLACEHOLDER BELOW — old schema for reference (can delete):
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  full_name text,
  birth_date date,
  sex text check (sex in ('male', 'female')),
  current_weight decimal,
  height decimal,
  activity_level text check (activity_level in ('sedentary', 'moderate', 'active')),
  tdee integer,
  target_calories integer,
  target_water_ml integer default 2500
);

-- 2. Food logs
create table if not exists public.food_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  food_name text not null,
  meal_type text check (meal_type in ('breakfast', 'lunch', 'dinner', 'snack')),
  calories integer not null,
  protein decimal,
  carbs decimal,
  fat decimal
);

-- 3. Water logs
create table if not exists public.water_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  date date default current_date not null,
  amount_ml integer not null
);

-- 4. Weight history
create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  date date default current_date not null,
  weight decimal not null,
  unique(user_id, date)
);

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.food_logs enable row level security;
alter table public.water_logs enable row level security;
alter table public.weight_logs enable row level security;

-- Profiles policies
create policy "Users can view own profile"
  on public.profiles for select using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

-- Food logs policies
create policy "Users can view own food logs"
  on public.food_logs for select using (auth.uid() = user_id);

create policy "Users can insert own food logs"
  on public.food_logs for insert with check (auth.uid() = user_id);

create policy "Users can delete own food logs"
  on public.food_logs for delete using (auth.uid() = user_id);

-- Water logs policies
create policy "Users can view own water logs"
  on public.water_logs for select using (auth.uid() = user_id);

create policy "Users can insert own water logs"
  on public.water_logs for insert with check (auth.uid() = user_id);

-- Weight logs policies
create policy "Users can view own weight logs"
  on public.weight_logs for select using (auth.uid() = user_id);

create policy "Users can insert own weight logs"
  on public.weight_logs for insert with check (auth.uid() = user_id);

create policy "Users can update own weight logs"
  on public.weight_logs for update using (auth.uid() = user_id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Indexes for performance
create index if not exists food_logs_user_created_idx on public.food_logs(user_id, created_at);
create index if not exists water_logs_user_date_idx on public.water_logs(user_id, date);
create index if not exists weight_logs_user_date_idx on public.weight_logs(user_id, date);
